"""Add meal type.

Revision ID: 2a073ad2dbd8
Revises: e24595c0d60b
Create Date: 2023-12-06 14:37:58.534809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a073ad2dbd8'
down_revision = 'e24595c0d60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('meal_type')

    # ### end Alembic commands ###
